version: '3.8'

services:
  frontend:
    build: .
    container_name: laravel-frontend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - APP_ENV=local
      - APP_KEY=base64:random-key
