name: CICD Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup PHP
      uses: shivammathur/setup-php@2.29.0
      with:
        php-version: '8.2'
    - name: Install Dependencies
      run: composer install --no-dev --no-interaction --no-progress --prefer-dist
    - name: Generate Key
      run: php artisan key:generate
    - name: Set Permissions
      run: chmod -R 777 storage bootstrap/cache

  deploy-staging:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Deploy to Staging via SSH
      uses: appleboy/ssh-action@v1.2.1
      with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.KEY }}
          username: hamda
          port: 22
          script: |
            ./frontend-gtp.sh
